package com.model;

// Generated 23 mars 2015 12:42:15 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Courrier generated by hbm2java
 */
@Entity
@Table(name = "courrier", catalog = "courrier")
public class Courrier implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Pochette pochette;
	private User userByDfuid;
	private User userByChfuid;
	private User userByChuid;
	private User userByChiuid;
	private String type;
	private String nature;
	private String montant;
	private Date initdate;
	private Date finaldate;
	private Integer etat;
	private String motif;
	private Set<Mode> modes = new HashSet<Mode>(0);

	public Courrier() {
	}

	public Courrier(Pochette pochette, User userByDfuid, User userByChfuid,
			User userByChuid, User userByChiuid, String type, String nature,
			String montant, Date initdate) {
		this.pochette = pochette;
		this.userByDfuid = userByDfuid;
		this.userByChfuid = userByChfuid;
		this.userByChuid = userByChuid;
		this.userByChiuid = userByChiuid;
		this.type = type;
		this.nature = nature;
		this.montant = montant;
		this.initdate = initdate;
	}

	public Courrier(Pochette pochette, User userByDfuid, User userByChfuid,
			User userByChuid, User userByChiuid, String type, String nature,
			String montant, Date initdate, Date finaldate, Integer etat,
			String motif, Set<Mode> modes) {
		this.pochette = pochette;
		this.userByDfuid = userByDfuid;
		this.userByChfuid = userByChfuid;
		this.userByChuid = userByChuid;
		this.userByChiuid = userByChiuid;
		this.type = type;
		this.nature = nature;
		this.montant = montant;
		this.initdate = initdate;
		this.finaldate = finaldate;
		this.etat = etat;
		this.motif = motif;
		this.modes = modes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid", nullable = false)
	public Pochette getPochette() {
		return this.pochette;
	}

	public void setPochette(Pochette pochette) {
		this.pochette = pochette;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dfuid", nullable = false)
	public User getUserByDfuid() {
		return this.userByDfuid;
	}

	public void setUserByDfuid(User userByDfuid) {
		this.userByDfuid = userByDfuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chfuid", nullable = false)
	public User getUserByChfuid() {
		return this.userByChfuid;
	}

	public void setUserByChfuid(User userByChfuid) {
		this.userByChfuid = userByChfuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chuid", nullable = false)
	public User getUserByChuid() {
		return this.userByChuid;
	}

	public void setUserByChuid(User userByChuid) {
		this.userByChuid = userByChuid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chiuid", nullable = false)
	public User getUserByChiuid() {
		return this.userByChiuid;
	}

	public void setUserByChiuid(User userByChiuid) {
		this.userByChiuid = userByChiuid;
	}

	@Column(name = "type", nullable = false, length = 250)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "nature", nullable = false, length = 250)
	public String getNature() {
		return this.nature;
	}

	public void setNature(String nature) {
		this.nature = nature;
	}

	@Column(name = "montant", nullable = false, length = 16777215)
	public String getMontant() {
		return this.montant;
	}

	public void setMontant(String montant) {
		this.montant = montant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "initdate", nullable = false, length = 0)
	public Date getInitdate() {
		return this.initdate;
	}

	public void setInitdate(Date initdate) {
		this.initdate = initdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finaldate", length = 0)
	public Date getFinaldate() {
		return this.finaldate;
	}

	public void setFinaldate(Date finaldate) {
		this.finaldate = finaldate;
	}

	@Column(name = "etat")
	public Integer getEtat() {
		return this.etat;
	}

	public void setEtat(Integer etat) {
		this.etat = etat;
	}

	@Column(name = "motif", length = 250)
	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "courrier")
	public Set<Mode> getModes() {
		return this.modes;
	}

	public void setModes(Set<Mode> modes) {
		this.modes = modes;
	}

}
