package com.model;

// Generated 23 mars 2015 12:42:15 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Loc generated by hbm2java
 */
@Entity
@Table(name = "loc", catalog = "courrier")
public class Loc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private User user;
	private String lbl;
	private String type;
	private String lblzone;

	public Loc() {
	}

	public Loc(User user, String lbl, String type, String lblzone) {
		this.user = user;
		this.lbl = lbl;
		this.type = type;
		this.lblzone = lblzone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uid", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "lbl", nullable = false, length = 250)
	public String getLbl() {
		return this.lbl;
	}

	public void setLbl(String lbl) {
		this.lbl = lbl;
	}

	@Column(name = "type", nullable = false, length = 60)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "lblzone", nullable = false, length = 250)
	public String getLblzone() {
		return this.lblzone;
	}

	public void setLblzone(String lblzone) {
		this.lblzone = lblzone;
	}

}
