package com.model;

// Generated 16 mars 2015 15:21:06 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String login;
	private String pw;
	private String prenom;
	private String nom;
	private String cin;
	private String adress;
	private String tel;
	private Set<Loc> locs = new HashSet<Loc>(0);

	public User() {
	}

	public User(String login, String pw, String prenom, String nom, String cin,
			String adress, String tel) {
		this.login = login;
		this.pw = pw;
		this.prenom = prenom;
		this.nom = nom;
		this.cin = cin;
		this.adress = adress;
		this.tel = tel;
	}

	public User(String login, String pw, String prenom, String nom, String cin,
			String adress, String tel, Set<Loc> locs) {
		this.login = login;
		this.pw = pw;
		this.prenom = prenom;
		this.nom = nom;
		this.cin = cin;
		this.adress = adress;
		this.tel = tel;
		this.locs = locs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "login", unique = true, nullable = false, length = 60)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "pw", nullable = false, length = 60)
	public String getPw() {
		return this.pw;
	}

	public void setPw(String pw) {
		this.pw = pw;
	}

	@Column(name = "prenom", nullable = false, length = 120)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "nom", nullable = false, length = 120)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "cin", nullable = false, length = 10)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Column(name = "adress", nullable = false, length = 250)
	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	@Column(name = "tel", nullable = false, length = 20)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Loc> getLocs() {
		return this.locs;
	}

	public void setLocs(Set<Loc> locs) {
		this.locs = locs;
	}

}
